<?xml version="1.0" encoding="utf-8"?>
<ArrayOfMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Message>
	<Recepients />
	<Body>Incoming message text</Body>
	<IsIncoming>true</IsIncoming>
	<IsRead>true</IsRead>
	<Attachments />
	<LocalTimestamp>131329488253575474</LocalTimestamp>
	<Sender>+40000000001</Sender>
</Message>
<Message>
	<Recepients>
		<string>+40000000001</string>
	</Recepients>
	<Body>Outgoing message text</Body>
	<IsIncoming>false</IsIncoming>
	<IsRead>true</IsRead>
	<Attachments />
	<LocalTimestamp>131329488070946809</LocalTimestamp>
	<Sender />
</Message>
<Message>
	<Recepients>
		<string>+40000000001</string>
		<string>+40000000002</string>
		<string>+40000000003</string>
	</Recepients>
	<Body>Outgoing (multiple) message text</Body>
	<IsIncoming>false</IsIncoming>
	<IsRead>true</IsRead>
	<Attachments />
	<LocalTimestamp>131329488070946809</LocalTimestamp>
	<Sender />
</Message>
</ArrayOfMessage>